In [9]:
import pandas as pd
import os

os.listdir("../data/raw")

['C2024_A.zip', '.DS_Store', 'HD2024.zip']

In [10]:
hd = pd.read_csv("../data/raw/HD2024.zip", encoding="latin1")
hd.head()

,ï»¿UNITID,INSTNM,IALIAS,ADDR,CITY,STABBR,ZIP,FIPS,OBEREG,CHFNM,...,CBSA,CBSATYPE,CSA,COUNTYCD,COUNTYNM,CNGDSTCD,LONGITUD,LATITUDE,DFRCGID,DFRCUSCG
0,100654,Alabama A & M University,AAMU,4900 Meridian Street,Normal,AL,35762,1,5,Dr. Daniel K. Wims,...,26620,1,290,1089,Madison County,105,-86.568502,34.783368,106,1
1,100663,University of Alabama at Birmingham,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,1,5,Ray L. Watts,...,13820,1,142,1073,Jefferson County,107,-86.799345,33.505697,91,1
2,100690,Amridge University,Southern Christian University Regions University,1200 Taylor Rd,Montgomery,AL,36117-3553,1,5,Michael C.Turner,...,33860,1,388,1101,Montgomery County,102,-86.174010,32.362609,125,2
3,100706,University of Alabama in Huntsville,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,1,5,Chuck Karr,...,26620,1,290,1089,Madison County,105,-86.640449,34.724557,91,2
4,100724,Alabama State University,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,1,5,Quinton T. Ross,...,33860,1,388,1101,Montgomery County,102,-86.295677,32.364317,97,1

In [11]:
hd.shape

(6072, 72)

In [12]:
hd.columns.tolist()

['ï»¿UNITID',
 'INSTNM',
 'IALIAS',
 'ADDR',
 'CITY',
 'STABBR',
 'ZIP',
 'FIPS',
 'OBEREG',
 'CHFNM',
 'CHFTITLE',
 'GENTELE',
 'EIN',
 'UEIS',
 'OPEID',
 'OPEFLAG',
 'WEBADDR',
 'ADMINURL',
 'FAIDURL',
 'APPLURL',
 'NPRICURL',
 'VETURL',
 'ATHURL',
 'DISAURL',
 'SECTOR',
 'ICLEVEL',
 'CONTROL',
 'HLOFFER',
 'UGOFFER',
 'GROFFER',
 'HDEGOFR1',
 'DEGGRANT',
 'HBCU',
 'HOSPITAL',
 'MEDICAL',
 'TRIBAL',
 'LOCALE',
 'OPENPUBL',
 'ACT',
 'NEWID',
 'DEATHYR',
 'CLOSEDAT',
 'CYACTIVE',
 'POSTSEC',
 'PSEFLAG',
 'PSET4FLG',
 'RPTMTH',
 'INSTCAT',
 'C00CARNEGIE',
 'C21BASIC',
 'CARNEGIEIC',
 'CARNEGIESAEC',
 'CARNEGIERSCH',
 'CARNEGIESIZE',
 'CARNEGIEALF',
 'CARNEGIEAPM',
 'CARNEGIEGPM',
 'LANDGRNT',
 'INSTSIZE',
 'F1SYSTYP',
 'F1SYSNAM',
 'F1SYSCOD',
 'CBSA',
 'CBSATYPE',
 'CSA',
 'COUNTYCD',
 'COUNTYNM',
 'CNGDSTCD',
 'LONGITUD',
 'LATITUDE',
 'DFRCGID',
 'DFRCUSCG']

In [13]:
hd.info()

<class 'pandas.DataFrame'>
RangeIndex: 6072 entries, 0 to 6071
Data columns (total 72 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ï»¿UNITID     6072 non-null   int64
 1   INSTNM        6072 non-null   str
 2   IALIAS        2193 non-null   str
 3   ADDR          6061 non-null   str
 4   CITY          6072 non-null   str
 5   STABBR        6072 non-null   str
 6   ZIP           6072 non-null   str
 7   FIPS          6072 non-null   int64
 8   OBEREG        6072 non-null   int64
 9   CHFNM         6001 non-null   str
 10  CHFTITLE      6001 non-null   str
 11  GENTELE       6001 non-null   float64
 12  EIN           6072 non-null   int64
 13  UEIS          5537 non-null   str
 14  OPEID         6071 non-null   float64
 15  OPEFLAG       6072 non-null   int64
 16  WEBADDR       6001 non-null   str
 17  ADMINURL      5241 non-null   str
 18  FAIDURL       5240 non-null   str
 19  APPLURL       4794 non-null   str
 20  NPRICURL      5872 non-null   str
 21  VETURL        3783 non-null   str
 22  ATHURL        1713 non-null   str
 23  DISAURL       5959 non-null   str
 24  SECTOR        6072 non-null   int64
 25  ICLEVEL       6072 non-null   int64
 26  CONTROL       6072 non-null   int64
 27  HLOFFER       6072 non-null   int64
 28  UGOFFER       6072 non-null   int64
 29  GROFFER       6072 non-null   int64
 30  HDEGOFR1      6072 non-null   int64
 31  DEGGRANT      6072 non-null   int64
 32  HBCU          6072 non-null   int64
 33  HOSPITAL      6072 non-null   int64
 34  MEDICAL       6072 non-null   int64
 35  TRIBAL        6072 non-null   int64
 36  LOCALE        6072 non-null   int64
 37  OPENPUBL      6072 non-null   int64
 38  ACT           6072 non-null   str
 39  NEWID         6072 non-null   int64
 40  DEATHYR       6072 non-null   int64
 41  CLOSEDAT      6072 non-null   str
 42  CYACTIVE      6072 non-null   int64
 43  POSTSEC       6072 non-null   int64
 44  PSEFLAG       6072 non-null   int64
 45  PSET4FLG      6072 non-null   int64
 46  RPTMTH        6072 non-null   int64
 47  INSTCAT       6072 non-null   int64
 48  C00CARNEGIE   6072 non-null   int64
 49  C21BASIC      6072 non-null   int64
 50  CARNEGIEIC    6072 non-null   int64
 51  CARNEGIESAEC  6072 non-null   int64
 52  CARNEGIERSCH  6072 non-null   int64
 53  CARNEGIESIZE  6072 non-null   int64
 54  CARNEGIEALF   6072 non-null   int64
 55  CARNEGIEAPM   6072 non-null   int64
 56  CARNEGIEGPM   6072 non-null   int64
 57  LANDGRNT      6072 non-null   int64
 58  INSTSIZE      6072 non-null   int64
 59  F1SYSTYP      6072 non-null   int64
 60  F1SYSNAM      6072 non-null   str
 61  F1SYSCOD      6072 non-null   int64
 62  CBSA          6072 non-null   int64
 63  CBSATYPE      6072 non-null   int64
 64  CSA           6072 non-null   int64
 65  COUNTYCD      6072 non-null   int64
 66  COUNTYNM      6069 non-null   str
 67  CNGDSTCD      6072 non-null   int64
 68  LONGITUD      6072 non-null   float64
 69  LATITUDE      6072 non-null   float64
 70  DFRCGID       6072 non-null   int64
 71  DFRCUSCG      6072 non-null   int64
dtypes: float64(4), int64(47), str(21)
memory usage: 3.3 MB

In [25]:
hd.columns = hd.columns.str.replace("ï»¿", "", regex=False)
columns_needed = [
    "UNITID",
    "INSTNM",
    "STABBR",
    "COUNTYNM",
    "CONTROL",
    "ICLEVEL",
    "LATITUDE",
    "LONGITUD"
]

institutions = hd[columns_needed].copy()
institutions.head()

,UNITID,INSTNM,STABBR,COUNTYNM,CONTROL,ICLEVEL,LATITUDE,LONGITUD
0,100654,Alabama A & M University,AL,Madison County,1,1,34.783368,-86.568502
1,100663,University of Alabama at Birmingham,AL,Jefferson County,1,1,33.505697,-86.799345
2,100690,Amridge University,AL,Montgomery County,2,1,32.362609,-86.174010
3,100706,University of Alabama in Huntsville,AL,Madison County,1,1,34.724557,-86.640449
4,100724,Alabama State University,AL,Montgomery County,1,1,32.364317,-86.295677

In [26]:
ca_institutions = institutions[
    institutions["STABBR"] == "CA"
].copy()

ca_public = ca_institutions[
    ca_institutions["CONTROL"] == 1
].copy()

ca_public_4yr = ca_public[
    ca_public["ICLEVEL"] == 1
].copy()

ca_public_4yr[["UNITID", "INSTNM", "COUNTYNM"]]

,UNITID,INSTNM,COUNTYNM
175,109350,Antelope Valley Community College District,Los Angeles County
180,109819,Bakersfield College,Kern County
192,110398,University of California College of the Law-Sa...,San Francisco County
195,110422,California Polytechnic State University-San Lu...,San Luis Obispo County
197,110486,California State University-Bakersfield,Kern County
...,...,...,...
4002,409698,California State University-Monterey Bay,Monterey County
4264,438665,Rancho Santiago Community College District Office,Orange County
4347,441937,California State University-Channel Islands,Ventura County
4454,445188,University of California-Merced,Merced County
5523,488800,Teachers College of San Joaquin,San Joaquin County

In [27]:
ca_public_4yr.shape

(68, 8)

In [28]:
uc_csu_names = [
    # University of California
    "University of California-Berkeley",
    "University of California-Davis",
    "University of California-Irvine",
    "University of California-Los Angeles",
    "University of California-Merced",
    "University of California-Riverside",
    "University of California-San Diego",
    "University of California-San Francisco",
    "University of California-Santa Barbara",
    "University of California-Santa Cruz",

    # California State University
    "California State University-Bakersfield",
    "California State University-Channel Islands",
    "California State University-Chico",
    "California State University-Dominguez Hills",
    "California State University-East Bay",
    "California State University-Fresno",
    "California State University-Fullerton",
    "California State Polytechnic University-Humboldt",
    "California State University-Long Beach",
    "California State University-Los Angeles",
    "California State University Maritime Academy",
    "California State University-Monterey Bay",
    "California State University-Northridge",
    "California State Polytechnic University-Pomona",
    "California State University-Sacramento",
    "California State University-San Bernardino",
    "San Diego State University",
    "San Francisco State University",
    "San Jose State University",
    "California Polytechnic State University-San Luis Obispo",
    "California State University-San Marcos",
    "Sonoma State University",
    "California State University-Stanislaus"
]

uc_csu = ca_public_4yr[
    ca_public_4yr["INSTNM"].isin(uc_csu_names)
].copy()

uc_csu = uc_csu.sort_values("INSTNM")

print("Number of institutions:", len(uc_csu))

uc_csu[
    ["UNITID", "INSTNM", "COUNTYNM", "LATITUDE", "LONGITUD"]
]

Number of institutions: 33

,UNITID,INSTNM,COUNTYNM,LATITUDE,LONGITUD
195,110422,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
308,115755,California State Polytechnic University-Humboldt,Humboldt County,40.877481,-124.078293
201,110529,California State Polytechnic University-Pomona,Los Angeles County,34.057912,-117.821476
225,111188,California State University Maritime Academy,Solano County,38.069061,-122.231551
197,110486,California State University-Bakersfield,Kern County,35.350005,-119.104711
4347,441937,California State University-Channel Islands,Ventura County,34.162949,-119.043560
202,110538,California State University-Chico,Butte County,39.729712,-121.844859
203,110547,California State University-Dominguez Hills,Los Angeles County,33.864766,-118.255917
206,110574,California State University-East Bay,Alameda County,37.657694,-122.054135
204,110556,California State University-Fresno,Fresno County,36.811154,-119.744569
205,110565,California State University-Fullerton,Orange County,33.881506,-117.885446
207,110583,California State University-Long Beach,Los Angeles County,33.782818,-118.112040
208,110592,California State University-Los Angeles,Los Angeles County,34.066927,-118.168965
4002,409698,California State University-Monterey Bay,Monterey County,36.652397,-121.796178
209,110608,California State University-Northridge,Los Angeles County,34.240126,-118.529319
210,110617,California State University-Sacramento,Sacramento County,38.559415,-121.423549
200,110510,California State University-San Bernardino,San Bernardino County,34.182622,-117.323801
3770,366711,California State University-San Marcos,San Diego County,33.130569,-117.159013
198,110495,California State University-Stanislaus,Stanislaus County,37.525770,-120.852511
420,122409,San Diego State University,San Diego County,32.775250,-117.071228
423,122597,San Francisco State University,San Francisco County,37.721224,-122.476799
432,122755,San Jose State University,Santa Clara County,37.336569,-121.880621
454,123572,Sonoma State University,Sonoma County,38.340274,-122.677066
211,110635,University of California-Berkeley,Alameda County,37.871918,-122.260463
212,110644,University of California-Davis,Yolo County,38.539667,-121.749567
213,110653,University of California-Irvine,Orange County,33.648434,-117.841248
214,110662,University of California-Los Angeles,Los Angeles County,34.071780,-118.442179
4454,445188,University of California-Merced,Merced County,37.366237,-120.424944
215,110671,University of California-Riverside,Riverside County,33.972460,-117.327410
216,110680,University of California-San Diego,San Diego County,32.877749,-117.235866
217,110699,University of California-San Francisco,San Francisco County,37.763737,-122.458489
218,110705,University of California-Santa Barbara,Santa Barbara County,34.416297,-119.846426
219,110714,University of California-Santa Cruz,Santa Cruz County,36.995584,-122.058801

In [29]:
missing = [
    name for name in uc_csu_names
    if name not in ca_public_4yr["INSTNM"].values
]

print("Names not found:")
print(missing)

Names not found:
[]

In [31]:
import zipfile

zip_path = "../data/raw/C2024_A.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    print(z.namelist())

['c2024_a.csv', 'c2024_a_rv.csv']

In [33]:
zip_path = "../data/raw/C2024_A.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    completions = pd.read_csv(
        z.open("c2024_a.csv"),
        encoding="latin1"
    )

print(completions.shape)
completions.head()

(307707, 64)

,ï»¿UNITID,CIPCODE,MAJORNUM,AWLEVEL,XCTOTALT,CTOTALT,XCTOTALM,CTOTALM,XCTOTALW,CTOTALW,...,XCUNKNM,CUNKNM,XCUNKNW,CUNKNW,XCNRALT,CNRALT,XCNRALM,CNRALM,XCNRALW,CNRALW
0,100654,1.0999,1,5,R,12,R,2,R,10,...,Z,0,Z,0,Z,0,Z,0,Z,0
1,100654,1.1001,1,5,R,10,R,1,R,9,...,Z,0,Z,0,Z,0,Z,0,Z,0
2,100654,1.1001,1,7,R,7,R,1,R,6,...,Z,0,Z,0,R,2,R,1,R,1
3,100654,1.1001,1,17,R,6,R,3,R,3,...,R,0,R,2,R,3,R,2,R,1
4,100654,1.9999,1,5,R,2,R,1,R,1,...,Z,0,Z,0,Z,0,Z,0,Z,0

In [34]:
completions.columns = completions.columns.str.replace("ï»¿", "", regex=False)
print(completions.columns.tolist())

['UNITID', 'CIPCODE', 'MAJORNUM', 'AWLEVEL', 'XCTOTALT', 'CTOTALT', 'XCTOTALM', 'CTOTALM', 'XCTOTALW', 'CTOTALW', 'XCAIANT', 'CAIANT', 'XCAIANM', 'CAIANM', 'XCAIANW', 'CAIANW', 'XCASIAT', 'CASIAT', 'XCASIAM', 'CASIAM', 'XCASIAW', 'CASIAW', 'XCBKAAT', 'CBKAAT', 'XCBKAAM', 'CBKAAM', 'XCBKAAW', 'CBKAAW', 'XCHISPT', 'CHISPT', 'XCHISPM', 'CHISPM', 'XCHISPW', 'CHISPW', 'XCNHPIT', 'CNHPIT', 'XCNHPIM', 'CNHPIM', 'XCNHPIW', 'CNHPIW', 'XCWHITT', 'CWHITT', 'XCWHITM', 'CWHITM', 'XCWHITW', 'CWHITW', 'XC2MORT', 'C2MORT', 'XC2MORM', 'C2MORM', 'XC2MORW', 'C2MORW', 'XCUNKNT', 'CUNKNT', 'XCUNKNM', 'CUNKNM', 'XCUNKNW', 'CUNKNW', 'XCNRALT', 'CNRALT', 'XCNRALM', 'CNRALM', 'XCNRALW', 'CNRALW']

In [36]:
completions_small = completions[
    [
        "UNITID",
        "CIPCODE",
        "AWLEVEL",
        "CTOTALT"
    ]
].copy()

uc_csu_completions = completions_small.merge(
    uc_csu[
        [
            "UNITID",
            "INSTNM",
            "COUNTYNM",
            "LATITUDE",
            "LONGITUD"
        ]
    ],
    on="UNITID",
    how="inner"
)


print(uc_csu_completions.shape)

uc_csu_completions.head(10)

(6166, 8)

,UNITID,CIPCODE,AWLEVEL,CTOTALT,INSTNM,COUNTYNM,LATITUDE,LONGITUD
0,110422,1.0000,5,36,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
1,110422,1.0000,7,12,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
2,110422,1.0101,5,0,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
3,110422,1.0101,7,0,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
4,110422,1.0102,5,117,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
5,110422,1.0102,7,0,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
6,110422,1.0102,5,1,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
7,110422,1.0201,5,30,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
8,110422,1.0603,5,0,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311
9,110422,1.0802,5,35,California Polytechnic State University-San Lu...,San Luis Obispo County,35.299513,-120.657311

In [37]:
uc_csu_completions["INSTNM"].nunique()

33

In [39]:
uc_csu_completions["AWLEVEL"].value_counts().sort_index()

AWLEVEL
5     3212
6      313
7     1807
8       85
17     697
18      52
Name: count, dtype: int64

In [41]:
degree_completions = uc_csu_completions[
    uc_csu_completions["AWLEVEL"].isin([5, 7, 17, 18])
].copy()

award_labels = {
    5: "Bachelor's degree",
    7: "Master's degree",
    17: "Doctor's - research/scholarship",
    18: "Doctor's - professional practice"
}

degree_completions["AWARD_NAME"] = (
    degree_completions["AWLEVEL"].map(award_labels)
)

degree_completions[
    ["INSTNM", "CIPCODE", "AWARD_NAME", "CTOTALT"]
].head(20)

,INSTNM,CIPCODE,AWARD_NAME,CTOTALT
0,California Polytechnic State University-San Lu...,1.0000,Bachelor's degree,36
1,California Polytechnic State University-San Lu...,1.0000,Master's degree,12
2,California Polytechnic State University-San Lu...,1.0101,Bachelor's degree,0
3,California Polytechnic State University-San Lu...,1.0101,Master's degree,0
4,California Polytechnic State University-San Lu...,1.0102,Bachelor's degree,117
5,California Polytechnic State University-San Lu...,1.0102,Master's degree,0
6,California Polytechnic State University-San Lu...,1.0102,Bachelor's degree,1
7,California Polytechnic State University-San Lu...,1.0201,Bachelor's degree,30
8,California Polytechnic State University-San Lu...,1.0603,Bachelor's degree,0
9,California Polytechnic State University-San Lu...,1.0802,Bachelor's degree,35
10,California Polytechnic State University-San Lu...,1.0901,Bachelor's degree,189
11,California Polytechnic State University-San Lu...,1.0905,Bachelor's degree,18
12,California Polytechnic State University-San Lu...,1.0905,Master's degree,0
13,California Polytechnic State University-San Lu...,1.1001,Bachelor's degree,42
14,California Polytechnic State University-San Lu...,1.1001,Master's degree,2
15,California Polytechnic State University-San Lu...,1.1004,Bachelor's degree,65
16,California Polytechnic State University-San Lu...,1.1102,Bachelor's degree,48
17,California Polytechnic State University-San Lu...,1.1102,Bachelor's degree,1
18,California Polytechnic State University-San Lu...,1.1103,Bachelor's degree,0
19,California Polytechnic State University-San Lu...,1.1201,Bachelor's degree,0

In [42]:
degree_completions.groupby("AWARD_NAME")["CTOTALT"].sum()

AWARD_NAME
Bachelor's degree                   342726
Doctor's - professional practice      5918
Doctor's - research/scholarship       9986
Master's degree                      73254
Name: CTOTALT, dtype: int64

In [44]:
cip = pd.read_csv("../data/raw/CIPCODE2020.csv")

print(cip.shape)
print(cip.columns.tolist())
cip.head()

(2848, 8)
['CIPFamily', 'CIPCode', 'Action', 'TextChange', 'CIPTitle', 'CIPDefinition', 'CrossReferences', 'Examples']

,CIPFamily,CIPCode,Action,TextChange,CIPTitle,CIPDefinition,CrossReferences,Examples
0,"=""01""","=""01""",No substantive changes,yes,AGRICULTURAL/ANIMAL/PLANT/VETERINARY SCIENCE A...,Instructional programs that focus on agricultu...,NaN,NaN
1,"=""01""","=""01.00""",No substantive changes,no,"Agriculture, General.",Instructional content is defined in code 01.0000.,NaN,NaN
2,"=""01""","=""01.0000""",No substantive changes,no,"Agriculture, General.",A program that focuses on the general principl...,14.0301 - Agricultural Engineering.,NaN
3,"=""01""","=""01.01""",No substantive changes,no,Agricultural Business and Management.,Instructional content for this group of progra...,NaN,NaN
4,"=""01""","=""01.0101""",No substantive changes,no,"Agricultural Business and Management, General.",A general program that focuses on modern busi...,NaN,NaN

In [52]:
cip["CIPCode"] = (
    cip["CIPCode"]
    .str.replace('="', '', regex=False)
    .str.replace('"', '', regex=False)
)

print(cip["CIPCode"].head(10).tolist())

['01', '01.00', '01.0000', '01.01', '01.0101', '01.0102', '01.0103', '01.0104', '01.0105', '01.0106']

In [56]:
degree_completions = degree_completions.drop(
    columns=["CIPCode_x", "CIPTitle_x", "CIPCode_y", "CIPTitle_y"]
)

print([col for col in degree_completions.columns if "CIP" in col])

['CIPCODE']

In [57]:
degree_completions = degree_completions.merge(
    cip[["CIPCode", "CIPTitle"]],
    left_on="CIPCODE",
    right_on="CIPCode",
    how="left"
)

print("Unmatched CIP codes:")
print(degree_completions["CIPTitle"].isna().sum())

Unmatched CIP codes:
146

In [58]:
unmatched_cips = degree_completions.loc[
    degree_completions["CIPTitle"].isna(),
    "CIPCODE"
].unique()

print(unmatched_cips)

<StringArray>
['99.0000']
Length: 1, dtype: str

In [59]:
degree_completions.loc[
    degree_completions["CIPCODE"] == "99.0000",
    ["INSTNM", "CIPCODE", "AWARD_NAME", "CTOTALT"]
].head(20)

,INSTNM,CIPCODE,AWARD_NAME,CTOTALT
156,California Polytechnic State University-San Lu...,99.0000,Bachelor's degree,4985
157,California Polytechnic State University-San Lu...,99.0000,Master's degree,544
158,California Polytechnic State University-San Lu...,99.0000,Bachelor's degree,38
159,California Polytechnic State University-San Lu...,99.0000,Master's degree,3
232,California State University-Bakersfield,99.0000,Bachelor's degree,2148
233,California State University-Bakersfield,99.0000,Master's degree,386
234,California State University-Bakersfield,99.0000,Doctor's - research/scholarship,7
235,California State University-Bakersfield,99.0000,Bachelor's degree,23
317,California State University-Stanislaus,99.0000,Bachelor's degree,2467
318,California State University-Stanislaus,99.0000,Master's degree,321
319,California State University-Stanislaus,99.0000,Doctor's - research/scholarship,12
320,California State University-Stanislaus,99.0000,Bachelor's degree,29
321,California State University-Stanislaus,99.0000,Master's degree,1
454,California State University-San Bernardino,99.0000,Bachelor's degree,4328
455,California State University-San Bernardino,99.0000,Master's degree,861
456,California State University-San Bernardino,99.0000,Doctor's - research/scholarship,11
457,California State University-San Bernardino,99.0000,Bachelor's degree,49
458,California State University-San Bernardino,99.0000,Master's degree,20
572,California State Polytechnic University-Pomona,99.0000,Bachelor's degree,5859
573,California State Polytechnic University-Pomona,99.0000,Master's degree,544

In [60]:
degree_completions = degree_completions[
    degree_completions["CIPCODE"] != "99.0000"
].copy()

print(degree_completions["CIPTitle"].isna().sum())

0

In [61]:
top_programs = (
    degree_completions
    .groupby(["CIPCODE", "CIPTitle"], as_index=False)["CTOTALT"]
    .sum()
    .sort_values("CTOTALT", ascending=False)
    .head(20)
)

top_programs

     CIPCODE                                           CIPTitle  CTOTALT
554  52.0201   Business Administration and Management, General.    23016
405  42.0101                               Psychology, General.    12798
103  11.0701                                  Computer Science.    10292
266  26.0101              Biology/Biological Sciences, General.     7712
461  45.1101                                Sociology, General.     6967
457  45.1001         Political Science and Government, General.     4547
367  31.0501  Sports, Kinesiology, and Physical Education/Fi...     4427
421  43.0104                   Criminal Justice/Safety Studies.     4129
174  14.1901                            Mechanical Engineering.     4113
260  24.0101         Liberal Arts and Sciences/Liberal Studies.     3950
447  45.0603           Econometrics and Quantitative Economics.     3733
81   09.0101                 Speech Communication and Rhetoric.     3639
545  51.3801               Registered Nursing/Registered Nurse.     3422
168  14.1001            Electrical and Electronics Engineering.     3316
252  23.0101          English Language and Literature, General.     3251
411  42.2799       Research and Experimental Psychology, Other.     2917
433  44.0701                                       Social Work.     2888
131  13.1210            Early Childhood Education and Teaching.     2848
529  51.2201                            Public Health, General.     2796
578  54.0101                                  History, General.     2693